apiVersion: batch/v1
kind: Job
metadata:
  name: certsync-job
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "450"
    # argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              {{ range $idx, $cluster := .Values.clusters }}
              export KUBECONFIG=/data/{{ .name }}-kubeconfig
              {{ include "cluster.login" $cluster | nindent 14 }}
              {{ include "certificates.gather" $cluster | nindent 14 }}
              unset KUBECONFIG
              {{ end }}


              if oc get cm -n openshift-config user-ca-bundle > /dev/null 2>&1; then
                echo oc get cm -n openshift-config user-ca-bundle -o jsonpath="{['data']['ca-bundle\.crt']}" >> /data/hub-existing-user-ca-bundle.crt || true
              fi

              cat <<EOF > /data/combined-ca-bundle.yaml
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: user-ca-bundle
                namespace: openshift-config
              data:
                ca-bundle.crt: |
              $(cat /data/*.crt|sed 's/^/    /')
              EOF

              oc apply -f /data/combined-ca-bundle.yaml
              oc patch proxy cluster --type=merge  --patch='{"spec":{"trustedCA":{"name":"user-ca-bundle"}}}'


              {{ range $idx, $cluster := .Values.clusters -}}
              export KUBECONFIG=/data/{{ .name }}-kubeconfig
              {{ include "certificates.sync" $cluster | nindent 14 }}
              unset KUBECONFIG
              {{- end }}

          volumeMounts:
            - name: workdir
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
      serviceAccountName: openshift-gitops-cntk-argocd-application-controller
  backoffLimit: 4
