apiVersion: batch/v1
kind: Job
metadata:
  name: secretsync-job
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "450"
    # argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: certpush
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/sh

              {{ range $idx, $cluster := .Values.clusters }}
              clusterSecret=$(oc get clusterdeployment {{ .name }} -n {{ .name }} -o jsonpath='{.spec.clusterMetadata.adminPasswordSecretRef.name}')
              username=$(oc get secret $clusterSecret  -n {{ .name }} -o jsonpath="{.data.username}" | base64 --decode)
              password=$(oc get secret $clusterSecret  -n {{ .name }} -o jsonpath="{.data.password}" | base64 --decode)
              apiURL=$(oc get clusterdeployment -n {{ .name }} -o jsonpath="{.items[0].status.apiURL}")
              export KUBECONFIG=/data/{{ .name }}-kubeconfig
              oc login ${apiURL} -u ${username} -p ${password} --insecure-skip-tls-verify
              AWS_ACCESS_KEY_ID=$(oc get secret odrbucket -n openshift-dr-system -o jsonpath='{.data.AWS_ACCESS_KEY_ID}')
              AWS_SECRET_ACCESS_KEY=$(oc get secret odrbucket -n openshift-dr-system -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}')
              unset KUBECONFIG

              cat <<EOF > /data/odr-s3secret-{{ .role }}.yaml
              apiVersion: v1
              data:
                AWS_ACCESS_KEY_ID: $(echo -n ${AWS_ACCESS_KEY_ID})
                AWS_SECRET_ACCESS_KEY: $(echo -n ${AWS_SECRET_ACCESS_KEY})
              kind: Secret
              metadata:
                name: odr-s3secret-{{ .role }}
                namespace: openshift-dr-system
              EOF

              {{ end }}
              ls -la /data/
              {{ range $idx, $cluster := .Values.clusters }}
              export KUBECONFIG=/data/{{ .name }}-kubeconfig
              oc apply -f /data/odr-s3secret-primary.yaml
              oc apply -f /data/odr-s3secret-secondary.yaml
              unset KUBECONFIG
              {{ end }}

          volumeMounts:
            - name: workdir
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
      serviceAccountName: openshift-gitops-cntk-argocd-application-controller
  backoffLimit: 4
