apiVersion: batch/v1
kind: Job
metadata:
  name: ramenpatch-job
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "450"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -c
            - |

              oc get configmap ramen-hub-operator-config -n openshift-dr-system  -o yaml | \
                egrep -v  "deploymentAutomationEnabled|s3SecretDistributionEnabled" | \
                sed 's/drClusterOperator:/drClusterOperator:\n      deploymentAutomationEnabled: true\n      s3SecretDistributionEnabled: true/' | \
                oc replace -f -

          volumeMounts:
            - name: workdir
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
      serviceAccountName: openshift-gitops-cntk-argocd-application-controller
  backoffLimit: 4
