apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ include "cluster.name" . }}
  namespace: {{ include "cluster.name" . }}
spec:
  clusterName: {{ include "cluster.name" . }}
  clusterNamespace: {{ include "cluster.name" . }}
  clusterLabels:
    name: {{ include "cluster.name" . }}
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
    # Apparently this isnt available in the latest API --> https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/clusters/cluster-lifecycle-architecture#modifying-the-klusterlet-add-ons-settings-of-your-cluster
    #argocdCluster: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true