apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ include "cluster.name" . }}
  namespace: {{ include "cluster.name" . }}
  labels:
    name: {{ include "cluster.name" . }}
    cloud: '{{ include "metadata.labels.cloud" . }}'
    vendor: '{{ include "cluster.vendor" . }}'
  annotations: {}
spec:
  hubAcceptsClient: true